### ISSUE TITLE
Check Validation

### ISSUE THREAD

**Issue by AntoniosMavropoulos** [David-Carrasco/Scrapy-Idealista#1]
Hello David,

Wonderful job on the scraper.
I have built a scraper of my own which follows links in order to get as much info as possible, but unfortunately the site redirects me to check validation (https://www.idealista.com/checkvalidation).
Your spider also does this, can you help on bypassing this?

With kind regards,
Antonios

**Comment by alvarolozano** [comment]
I made my own one too with JS... the solution was to wait between requests (minimum 30 seconds). If you want to enter the details page, it's more difficult,  I always get banned... There are some captcha bypassing services, but they are not free

**Comment by miguelrodriguezpro** [comment]
> I made my own one too with JS... the solution was to wait between requests (minimum 30 seconds). If you want to enter the details page, it's more difficult, I always get banned... There are some captcha bypassing services, but they are not free

interesting, i´ve bought for testing one of those services and it has api for js also. If you are interested you can DM me here or in telegram.  I am quite interested in scraping projects. Even though i am not an exert in JS. I prefer much more Python. 

Hope i hear from you soon.

**Comment by miguelrodriguezpro** [comment]
> I made my own one too with JS... the solution was to wait between requests (minimum 30 seconds). If you want to enter the details page, it's more difficult, I always get banned... There are some captcha bypassing services, but they are not free

i am experiencing good results with 4 secs of delay between requests (i´m using like a gui software, maybe that is the reson why)

**Comment by David-Carrasco** [comment]
#3

**Comment by David-Carrasco** [comment]
#3

**Comment by David-Carrasco** [comment]
.
